---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-niri-nvidia
# description will be included in the image's metadata
description: Personal Niri image based on Wayblue's image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/niri-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

modules:
  - type: dnf
 
    repos:
    - type: copr
      repo: avengemedia/dms

    - type: copr
      repo: solopasha/hyprland

    - type: repo
      url: https://packages.microsoft.com/yumrepos/vscode/config.repo
 
    install:
      packages:
        - dms
        - kitty
        - code
        - dolphin
        - ark
        - hyprqt6engine
 
    remove:
      packages:
        - alacritty

  - type: files
    files:
      - source: system/
        destination: /
      - source: home/
        destination: /etc/skel/
