---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-niri-nvidia
# description will be included in the image's metadata
description: Personal Niri image based on Wayblue's image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/niri-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

modules:
  - type: rpm-ostree
 
    repos:
      - https://copr.fedorainfracloud.org/coprs/avengemedia/dms/repo/fedora-%OS_VERSION%/avengemedia-dms-fedora-%OS_VERSION%.repo
 
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
 
    install:
      - dms
      - kitty
      - code
      - dolphin
      - ark
 
    remove:
      - alacritty

  - type: files
    files:
      - source: system/
        destination: /
      - source: home/
        destination: /etc/skel/
